### ISSUE TITLE
Application fails to render anything

### ISSUE THREAD

**Issue by Topnott** [PJB3005/Drizzle#26]
whenever I attempt to render a level, It spits out this error immediately:

[23:16:25 ERR] Exception while rendering!
Drizzle.Logic.Rendering.RenderCameraException: Exception on camera 1
 ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at CallSite.Target(Closure, CallSite, Object, Object)
   at Drizzle.Ported.MovieScript.setuplayer(Object layer) in /home/runner/work/Drizzle/Drizzle/Drizzle.Ported/Translated/Movie.levelRendering.cs:line 348
   at Drizzle.Logic.Rendering.LevelRenderer.RenderLayers() in /home/runner/work/Drizzle/Drizzle/Drizzle.Logic/Rendering/LevelRenderer.RenderCore.cs:line 160
   at Drizzle.Logic.Rendering.LevelRenderer.DoRender() in /home/runner/work/Drizzle/Drizzle/Drizzle.Logic/Rendering/LevelRenderer.RenderCore.cs:line 50
   --- End of inner exception stack trace ---
   at Drizzle.Logic.Rendering.LevelRenderer.DoRender() in /home/runner/work/Drizzle/Drizzle/Drizzle.Logic/Rendering/LevelRenderer.RenderCore.cs:line 85
   at Drizzle.Editor.ViewModels.Render.RenderViewModel.RenderThread() in /home/runner/work/Drizzle/Drizzle/Drizzle.Editor/ViewModels/Render/RenderViewModel.cs:line 241

**Comment by PJB3005** [comment]
What level are you trying to render? Also you're not trying to render any projects from 1.9 (Downpour) right?

**Comment by HenryMarkle** [comment]
It doesn't support Downpour content yet, right?

**Comment by HenryMarkle** [comment]
I'm facing the same exception. I believe that's the reason.
here's my level that I'm trying to render.

[SU2_A07.txt](https://github.com/PJB3005/Drizzle/files/12192498/SU2_A07.txt)
![SU2_A07](https://github.com/PJB3005/Drizzle/assets/133786213/133081e5-47d6-4f13-88c2-908a9d1990ec)

**Comment by PJB3005** [comment]
Yeah it doesn't support DP/Community stuff. I think Slime has a branch for it here, but i don't know the status of that: https://github.com/SlimeCubed/Drizzle
